project_id = "clsjdxwbsjbhjibvlqbz"

[functions.transcribe-audio]
verify_jwt = true

[functions.enhance-caption]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false

[functions.generate-media-report]
verify_jwt = true

[functions.send-receipt-notification]
verify_jwt = false

[functions.send-sms]
verify_jwt = true

[functions.send-training-notification]
verify_jwt = false

[functions.process-scheduled-sms]
verify_jwt = false

[functions.get-textbelt-key]
verify_jwt = true